name: Minification

on: push

jobs:

  minify:
    name: generating minified html/js/css
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: remove previous files
      run: |
        rm -r build/*
        rm -r minified/*

    - name: Auto Minify
      uses: nizarmah/auto-minify@master
      with:
        directory: source
        output: minified

    # Auto commits minified files to the repository
    # Ignore it if you don't want to commit the files to the repository 
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}

    - name: rename minified files
      run: |
        cd ./minified
        for file in *.min.* ; do mv $file ${file//min./} ; done
        cd ..
    - name: add minfied files to build directory
      run: |
        mkdir build
        cp -a minified/. build
    - name: copy index file from source to build
      run: |
        cp source/index.html build/index.html
        cp source/timer_page/timer.html build/timer.html
    - name: create timer_page directory structure
      run: |
        cd build
        mkdir timer_page
        mv break.js progress.js timer-modals.css timer.css timer.js timer.html timer_page
    - name: commit build files
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: "Github Action: Build Files"
        branch: ${{ github.ref }}
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        